// lib/seoTopics.js
// Base de sujets pour les pages SEO programmatiques /creer-un-ebook/[slug]

export function slugify(s) {
  return s
    .toLowerCase()
    .normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/['’]/g, " ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export const CATEGORIES = [
  { name: "Business en ligne", topics: ["Lancer son business en ligne sans capital", "Trouver une idée de business rentable", "Créer sa première source de revenus en ligne", "Vendre des produits digitaux", "Bâtir une marque personnelle", "Automatiser son business avec l'IA", "Passer du salariat à l'entrepreneuriat", "Créer un business depuis son téléphone", "Les bases de l'entrepreneuriat digital", "Monétiser une audience", "Lancer une activité complémentaire", "Construire un business à revenus récurrents", "Vendre ses services en ligne", "Créer une offre irrésistible", "Réussir son premier mois d'activité", "Développer un business à l'international"] },
  { name: "Marketing & réseaux sociaux", topics: ["Gagner ses premiers abonnés sur Instagram", "Créer du contenu qui engage", "Maîtriser TikTok pour vendre", "Faire de la publicité Facebook rentable", "Écrire des posts qui convertissent", "Construire une stratégie de contenu", "Devenir créateur de contenu", "Le copywriting pour vendre plus", "Lancer une chaîne YouTube", "Créer une newsletter qui fidélise", "Faire connaître sa marque sans budget", "Les secrets du marketing d'influence", "Transformer ses vues en ventes", "Maîtriser le personal branding", "Créer une communauté engagée", "Réussir un lancement produit"] },
  { name: "WhatsApp & vente directe", topics: ["Vendre sur WhatsApp Business", "Trouver des clients sur WhatsApp", "Le message qui fait acheter", "Créer un catalogue WhatsApp", "Conclure une vente par message", "Automatiser ses ventes WhatsApp", "Gérer une boutique WhatsApp", "Fidéliser ses clients sur WhatsApp", "Vendre grâce aux statuts WhatsApp", "Convertir un prospect en client", "Les scripts de vente par message", "Relancer un client sans être lourd", "Vendre en gros sur WhatsApp", "Construire une liste de diffusion", "Vendre des formations sur WhatsApp", "Créer la confiance à distance"] },
  { name: "E-commerce & dropshipping", topics: ["Démarrer le dropshipping en Afrique", "Trouver un produit gagnant", "Créer sa boutique en ligne", "Sourcer des produits rentables", "Gérer la livraison et la logistique", "Le marketing pour l'e-commerce", "Vendre sans stock", "Calculer ses marges", "Fidéliser ses acheteurs", "Lancer sa première boutique Shopify", "Trouver des fournisseurs fiables", "Réussir ses photos produits", "Gérer le service client", "Vendre des produits locaux en ligne", "Construire une marque e-commerce", "Faire grandir sa boutique"] },
  { name: "Freelance & métiers du digital", topics: ["Devenir freelance et trouver des clients", "Se lancer dans le graphisme", "Apprendre le montage vidéo", "Devenir community manager", "Se lancer dans la rédaction web", "Apprendre le développement web", "Devenir assistant virtuel", "Fixer ses tarifs en freelance", "Trouver des missions à l'étranger", "Créer un portfolio qui vend", "Gérer plusieurs clients", "Travailler en ligne depuis l'Afrique", "Apprendre le design sur Canva", "Devenir traducteur freelance", "Se lancer dans le marketing digital", "Vivre du freelancing"] },
  { name: "Finance personnelle", topics: ["Gérer son argent au quotidien", "Sortir de l'endettement", "Épargner même avec un petit revenu", "Créer son premier budget", "Augmenter ses revenus", "Les bases de la liberté financière", "Arrêter de vivre au jour le jour", "Investir ses premières économies", "Préparer sa retraite", "Gérer l'argent en couple", "Construire un fonds d'urgence", "Comprendre le crédit", "Multiplier ses sources de revenus", "Apprendre à investir intelligemment", "Atteindre ses objectifs financiers", "La psychologie de l'argent"] },
  { name: "Investissement & crypto", topics: ["Comprendre la crypto pour débutants", "Investir en bourse depuis l'Afrique", "Les bases du trading", "Acheter ses premiers bitcoins en sécurité", "Comprendre les stablecoins", "Investir sans se faire arnaquer", "Le forex pour débutants", "Construire un portefeuille d'investissement", "Comprendre la finance décentralisée", "Gérer le risque en trading", "Investir dans l'or", "Les NFT expliqués simplement", "Faire fructifier son épargne", "Comprendre les marchés financiers", "Trader avec une petite mise", "Éviter les pièges de la crypto"] },
  { name: "Immobilier", topics: ["Investir dans l'immobilier sans gros capital", "Acheter son premier terrain", "Construire sa maison étape par étape", "Devenir agent immobilier", "Louer un bien rentable", "Investir dans l'immobilier locatif", "Acheter un terrain en sécurité", "Gérer un bien locatif", "Les bases de l'immobilier", "Négocier l'achat d'un bien", "Investir dans l'immobilier à l'étranger", "Financer un projet immobilier", "Rénover pour revendre", "Comprendre les titres fonciers", "Devenir promoteur immobilier", "Générer des revenus passifs immobiliers"] },
  { name: "Agriculture & élevage", topics: ["Se lancer dans l'agriculture rentable", "Démarrer un élevage de poulets", "Cultiver et vendre ses légumes", "Se lancer dans la pisciculture", "Créer une ferme rentable", "Démarrer l'aviculture", "Cultiver le maïs efficacement", "Se lancer dans l'apiculture", "Élever des chèvres", "L'agriculture moderne pour débutants", "Transformer ses récoltes", "Vendre ses produits agricoles", "Démarrer un potager rentable", "Se lancer dans l'élevage de porcs", "Réussir la culture maraîchère", "Financer son projet agricole"] },
  { name: "Cuisine & restauration", topics: ["Lancer un business de cuisine à domicile", "Vendre ses plats en ligne", "Ouvrir un fast-food rentable", "Vendre des recettes africaines", "Démarrer une pâtisserie", "La cuisine pour débutants", "Créer un service de livraison de repas", "Vendre des jus et boissons naturelles", "Réussir ses pâtisseries maison", "Lancer un food truck", "Les recettes qui se vendent", "Cuisiner sain au quotidien", "Démarrer un service traiteur", "Vendre du pain et des viennoiseries", "Créer une marque alimentaire", "Conserver et transformer les aliments"] },
  { name: "Santé & bien-être", topics: ["Perdre du poids sans régime strict", "Manger sainement avec un petit budget", "Booster son énergie au quotidien", "Mieux dormir naturellement", "Gérer son stress", "Renforcer son immunité", "Les bienfaits des plantes médicinales", "Adopter de meilleures habitudes de vie", "Détoxifier son corps naturellement", "Prévenir les maladies courantes", "Prendre soin de sa santé mentale", "Vaincre la fatigue chronique", "Adopter une alimentation équilibrée", "Maigrir durablement", "Mieux comprendre son corps", "Vivre plus longtemps en bonne santé"] },
  { name: "Fitness & musculation", topics: ["Se muscler à la maison sans matériel", "Prendre de la masse musculaire", "Perdre du ventre", "Un programme fitness pour débutants", "S'entraîner sans salle de sport", "Sécher et se définir", "Les bases de la musculation", "La nutrition pour la prise de muscle", "Retrouver la forme après 40 ans", "Le fitness au féminin", "Construire une routine sportive", "Gagner en force", "S'étirer et éviter les blessures", "La callisthénie pour débutants", "Transformer son corps en 90 jours", "Rester motivé pour le sport"] },
  { name: "Développement personnel", topics: ["Vaincre la procrastination", "Développer sa confiance en soi", "Atteindre ses objectifs", "Gérer son temps efficacement", "Construire de bonnes habitudes", "Sortir de sa zone de confort", "Développer une mentalité de gagnant", "Apprendre à dire non", "Gérer ses émotions", "Trouver sa raison d'être", "Devenir discipliné", "Arrêter de se comparer aux autres", "Cultiver la gratitude", "Surmonter la peur de l'échec", "Devenir la meilleure version de soi", "La puissance des habitudes"] },
  { name: "Relations & couple", topics: ["Réussir sa vie de couple", "Reconquérir son ex", "Communiquer sans se disputer", "Raviver la flamme", "Mieux comprendre les hommes", "Mieux comprendre les femmes", "Construire une relation durable", "Gérer les conflits dans le couple", "Retrouver la complicité", "Préparer son mariage", "Surmonter une rupture", "Les clés d'un couple épanoui", "Séduire avec authenticité", "Gérer la jalousie", "Rebâtir la confiance", "Entretenir l'amour à distance"] },
  { name: "Parentalité & éducation", topics: ["Bien éduquer ses enfants", "Gérer les colères de l'enfant", "Accompagner la scolarité de son enfant", "Élever des enfants épanouis", "La discipline positive", "Préparer l'arrivée de bébé", "Aider son ado à réussir", "Développer l'autonomie de l'enfant", "Limiter le temps d'écran", "Renforcer le lien parent-enfant", "Gérer la fratrie", "Éveiller son enfant", "Accompagner les premières années", "Motiver son enfant à apprendre", "Devenir un meilleur parent", "Élever un enfant confiant"] },
  { name: "Spiritualité & foi", topics: ["Renforcer sa foi au quotidien", "Apprendre à prier efficacement", "Méditer la parole", "Trouver la paix intérieure", "Vivre selon ses valeurs", "Surmonter les épreuves par la foi", "Développer une vie de prière", "Comprendre sa mission de vie", "Cultiver la gratitude spirituelle", "Grandir spirituellement", "Garder la foi face aux difficultés", "Trouver un sens à sa vie", "Pratiquer le pardon", "Vivre une vie de gratitude", "Renforcer sa relation au divin", "Méditation et bien-être spirituel"] },
  { name: "Immigration & études à l'étranger", topics: ["Réussir son dossier de visa", "Étudier au Canada", "Immigrer en France", "Obtenir une bourse d'études", "Préparer son départ à l'étranger", "Réussir son entretien de visa", "Étudier en Europe", "Trouver un logement à l'étranger", "S'intégrer dans un nouveau pays", "Travailler à l'étranger", "Le guide de l'expatriation", "Apprendre une langue avant de partir", "Réussir ses démarches administratives", "Étudier aux États-Unis", "Financer ses études à l'étranger", "Réussir sa première année à l'étranger"] },
  { name: "Langues & compétences", topics: ["Apprendre l'anglais rapidement", "Parler anglais sans complexe", "Écrire un français correct", "Maîtriser l'espagnol", "Apprendre une langue par soi-même", "Réussir le TOEFL et l'IELTS", "Améliorer son expression écrite", "Prendre la parole en public", "Apprendre à coder", "Maîtriser Excel", "Améliorer sa mémoire", "Apprendre plus vite", "Réussir ses examens", "Enrichir son vocabulaire", "Apprendre l'informatique de base", "Communiquer avec impact"] },
  { name: "Beauté & mode", topics: ["Lancer sa marque de cosmétiques", "Fabriquer ses produits de beauté naturels", "Prendre soin de sa peau", "Les secrets d'une belle peau", "Se lancer dans la coiffure", "Créer sa marque de vêtements", "Devenir styliste", "Le maquillage pour débutantes", "Vendre des produits de beauté", "Prendre soin de ses cheveux naturels", "Lancer un salon de beauté", "Fabriquer son savon artisanal", "Créer sa routine beauté", "Devenir maquilleuse professionnelle", "Vendre de la mode en ligne", "Construire une marque beauté"] },
  { name: "Métiers & artisanat", topics: ["Se lancer dans la couture", "Apprendre la menuiserie", "Démarrer un atelier artisanal", "Vendre ses créations faites main", "Apprendre la photographie", "Devenir photographe professionnel", "Se lancer dans la décoration d'intérieur", "Créer des bijoux à vendre", "Apprendre la mécanique", "Démarrer une activité de bricolage", "Devenir électricien", "Lancer un service de nettoyage", "Apprendre la plomberie", "Vendre de l'artisanat local", "Créer une entreprise de services", "Transformer une passion en métier"] },
];

// Aplatissement + déduplication par slug
const _seen = new Set();
export const ALL_TOPICS = [];
for (const cat of CATEGORIES) {
  const categorieSlug = slugify(cat.name);
  for (const titre of cat.topics) {
    const slug = slugify(titre);
    if (_seen.has(slug)) continue;
    _seen.add(slug);
    ALL_TOPICS.push({ slug, titre, categorie: cat.name, categorieSlug });
  }
}

export const TOPICS_COUNT = ALL_TOPICS.length;

const _bySlug = new Map(ALL_TOPICS.map((t) => [t.slug, t]));
export function getTopicBySlug(slug) {
  return _bySlug.get(slug) || null;
}

export function getRelated(slug, n = 6) {
  const t = _bySlug.get(slug);
  if (!t) return [];
  return ALL_TOPICS.filter((x) => x.categorie === t.categorie && x.slug !== slug).slice(0, n);
}
